[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# API proxy to FastAPI backend
[[redirects]]
  from = "/api/*"
  to = "https://YOUR-FASTAPI-HOST/:splat"
  status = 200
  force = true

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
