[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  # Allow Auth0 public configuration in build output
  SECRETS_SCAN_OMIT_KEYS = "AUTH0_DOMAIN,AUTH0_CLIENT_ID,AUTH0_AUDIENCE"

# Redirect all requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
