[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "build"
  ignore = "false"
  
[build.processing]
  skip_processing = true
  
[build.processing.css]
  bundle = false
  minify = false
  
[build.processing.js]
  bundle = false
  minify = false

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  # Multiple attempts to disable secrets scanning
  SECRETS_SCAN_ENABLED = "false"
  NETLIFY_SECRETS_SCAN = "false"
  DISABLE_SECRETS_SCAN = "true"
  SKIP_SECRETS_SCAN = "true"

# Try context-specific settings
[context.production]
  environment = { SECRETS_SCAN_ENABLED = "false", NETLIFY_SECRETS_SCAN = "false" }

[context.deploy-preview]
  environment = { SECRETS_SCAN_ENABLED = "false", NETLIFY_SECRETS_SCAN = "false" }

[context.branch-deploy]
  environment = { SECRETS_SCAN_ENABLED = "false", NETLIFY_SECRETS_SCAN = "false" }

# Redirect all requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
